// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Big Data
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package local_project.cold_start_master_job_0_1;

import routines.Numeric;
import routines.DataOperation;
import routines.TalendDataGenerator;
import routines.TalendStringUtil;
import routines.TalendString;
import routines.StringHandling;
import routines.Relational;
import routines.TalendDate;
import routines.Mathematical;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;

@SuppressWarnings("unused")

/**
 * Job: COLD_START_MASTER_JOB Purpose: <br>
 * Description: This job create table pos_brute and pos_traitee with index <br>
 * 
 * @author user@talend.com
 * @version 7.2.1.20190523_1134-M6
 * @status
 */
public class COLD_START_MASTER_JOB implements TalendJob {

	protected static void logIgnoredError(String message, Throwable cause) {
		System.err.println(message);
		if (cause != null) {
			cause.printStackTrace();
		}

	}

	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}

	private final static String defaultCharset = java.nio.charset.Charset.defaultCharset().name();

	private final static String utf8Charset = "UTF-8";

	// contains type for every context property
	public class PropertiesWithType extends java.util.Properties {
		private static final long serialVersionUID = 1L;
		private java.util.Map<String, String> propertyTypes = new java.util.HashMap<>();

		public PropertiesWithType(java.util.Properties properties) {
			super(properties);
		}

		public PropertiesWithType() {
			super();
		}

		public void setContextType(String key, String type) {
			propertyTypes.put(key, type);
		}

		public String getContextType(String key) {
			return propertyTypes.get(key);
		}
	}

	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();

	// create application properties with default
	public class ContextProperties extends PropertiesWithType {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties) {
			super(properties);
		}

		public ContextProperties() {
			super();
		}

		public void synchronizeContext() {

		}

	}

	protected ContextProperties context = new ContextProperties(); // will be instanciated by MS.

	public ContextProperties getContext() {
		return this.context;
	}

	private final String jobVersion = "0.1";
	private final String jobName = "COLD_START_MASTER_JOB";
	private final String projectName = "LOCAL_PROJECT";
	public Integer errorCode = null;
	private String currentComponent = "";

	private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
	private final static java.util.Map<String, Object> junitGlobalMap = new java.util.HashMap<String, Object>();

	private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
	public final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();

	private RunStat runStat = new RunStat();

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";

	private final static String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

	public void setDataSources(java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources.entrySet()) {
			talendDataSources.put(dataSourceEntry.getKey(),
					new routines.system.TalendDataSource(dataSourceEntry.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}

	private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
	private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(new java.io.BufferedOutputStream(baos));

	public String getExceptionStackTrace() {
		if ("failure".equals(this.getStatus())) {
			errorMessagePS.flush();
			return baos.toString();
		}
		return null;
	}

	private Exception exception;

	public Exception getException() {
		if ("failure".equals(this.getStatus())) {
			return this.exception;
		}
		return null;
	}

	private class TalendException extends Exception {

		private static final long serialVersionUID = 1L;

		private java.util.Map<String, Object> globalMap = null;
		private Exception e = null;
		private String currentComponent = null;
		private String virtualComponentName = null;

		public void setVirtualComponentName(String virtualComponentName) {
			this.virtualComponentName = virtualComponentName;
		}

		private TalendException(Exception e, String errorComponent, final java.util.Map<String, Object> globalMap) {
			this.currentComponent = errorComponent;
			this.globalMap = globalMap;
			this.e = e;
		}

		public Exception getException() {
			return this.e;
		}

		public String getCurrentComponent() {
			return this.currentComponent;
		}

		public String getExceptionCauseMessage(Exception e) {
			Throwable cause = e;
			String message = null;
			int i = 10;
			while (null != cause && 0 < i--) {
				message = cause.getMessage();
				if (null == message) {
					cause = cause.getCause();
				} else {
					break;
				}
			}
			if (null == message) {
				message = e.getClass().getName();
			}
			return message;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				if (virtualComponentName != null && currentComponent.indexOf(virtualComponentName + "_") == 0) {
					globalMap.put(virtualComponentName + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				}
				globalMap.put(currentComponent + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				System.err.println("Exception in component " + currentComponent + " (" + jobName + ")");
			}
			if (!(e instanceof TDieException)) {
				if (e instanceof TalendException) {
					e.printStackTrace();
				} else {
					e.printStackTrace();
					e.printStackTrace(errorMessagePS);
					COLD_START_MASTER_JOB.this.exception = e;
				}
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass().getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(COLD_START_MASTER_JOB.this, new Object[] { e, currentComponent, globalMap });
							break;
						}
					}

					if (!(e instanceof TDieException)) {
					}
				} catch (Exception e) {
					this.e.printStackTrace();
				}
			}
		}
	}

	public void tCreateTable_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tCreateTable_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tCreateTable_2_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tCreateTable_2_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tDBInput_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		try {

			if (this.execStat) {
				runStat.updateStatOnConnection("OnComponentError1", 0, "error");
			}

			errorCode = null;
			tDBInput_2Process(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}

		} catch (Exception e) {
			e.printStackTrace();
		}

		tDBInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tDBInput_2_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tDBInput_2_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tCreateTable_1_onSubJobError(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tCreateTable_2_onSubJobError(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tDBInput_1_onSubJobError(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tDBInput_2_onSubJobError(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tCreateTable_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tCreateTable_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				/**
				 * [tCreateTable_1 begin ] start
				 */

				ok_Hash.put("tCreateTable_1", false);
				start_Hash.put("tCreateTable_1", System.currentTimeMillis());

				currentComponent = "tCreateTable_1";

				int tos_count_tCreateTable_1 = 0;

				/**
				 * [tCreateTable_1 begin ] stop
				 */

				/**
				 * [tCreateTable_1 main ] start
				 */

				currentComponent = "tCreateTable_1";

				try {
					String driverClass_tCreateTable_1 = "org.postgresql.Driver";
					String url_tCreateTable_1 = "jdbc:postgresql://" + "localhost" + ":" + "5432" + "/" + "ambulance";
					String dbUser_tCreateTable_1 = "postgres";

					String tableName_tCreateTable_1 = "pos_brute";
					String dbSchema_tCreateTable_1 = "public";
					if (dbSchema_tCreateTable_1 != null && dbSchema_tCreateTable_1.trim().length() != 0) {
						tableName_tCreateTable_1 = dbSchema_tCreateTable_1 + "\".\"" + tableName_tCreateTable_1;
					}
					java.lang.Class jdbcclazz_tCreateTable_1 = java.lang.Class.forName("org.postgresql.Driver");
					final String decryptedPassword_tCreateTable_1 = routines.system.PasswordEncryptUtil
							.decryptPassword("Wc5JN7QOl+hOSS4VvmpEAQ==");
					java.sql.Connection conn_tCreateTable_1 = java.sql.DriverManager.getConnection(url_tCreateTable_1,
							dbUser_tCreateTable_1, decryptedPassword_tCreateTable_1);

					boolean whetherExist_tCreateTable_1 = false;
					java.sql.DatabaseMetaData dbMetaData_tCreateTable_1 = conn_tCreateTable_1.getMetaData();
					java.sql.ResultSet rsTable_tCreateTable_1 = dbMetaData_tCreateTable_1.getTables(null, null, null,
							new String[] { "TABLE" });
					String defaultSchema_tCreateTable_1 = "public";
					if (dbSchema_tCreateTable_1 == null || dbSchema_tCreateTable_1.trim().length() == 0) {
						java.sql.Statement stmtSchema_tCreateTable_1 = conn_tCreateTable_1.createStatement();
						java.sql.ResultSet rsSchema_tCreateTable_1 = stmtSchema_tCreateTable_1
								.executeQuery("select current_schema() ");
						while (rsSchema_tCreateTable_1.next()) {
							defaultSchema_tCreateTable_1 = rsSchema_tCreateTable_1.getString("current_schema");
						}
						rsSchema_tCreateTable_1.close();
						stmtSchema_tCreateTable_1.close();
					}
					while (rsTable_tCreateTable_1.next()) {
						String table_tCreateTable_1 = rsTable_tCreateTable_1.getString("TABLE_NAME");
						String schema_tCreateTable_1 = rsTable_tCreateTable_1.getString("TABLE_SCHEM");
						if (table_tCreateTable_1.equals("pos_brute") && (schema_tCreateTable_1
								.equals(dbSchema_tCreateTable_1)
								|| ((dbSchema_tCreateTable_1 == null || dbSchema_tCreateTable_1.trim().length() == 0)
										&& defaultSchema_tCreateTable_1.equals(schema_tCreateTable_1)))) {
							whetherExist_tCreateTable_1 = true;
							break;
						}
					}
					rsTable_tCreateTable_1.close();
					if (!whetherExist_tCreateTable_1) {
						java.sql.Statement stmt_tCreateTable_1 = conn_tCreateTable_1.createStatement();
						stmt_tCreateTable_1.execute("CREATE TABLE \"" + tableName_tCreateTable_1
								+ "\"(\"id_vehicule\" SERIAL  not null ,\"DATE\" VARCHAR(19)  ,\"TIME\" VARCHAR ,\"RPM\" INT4 ,\"SPEED\" FLOAT4 ,\"RIGHT_FLASH\" INT4 ,\"LEFT_FLASH\" INT4 ,\"BRAKE_PEDAL\" INT4 ,\"PRIMARY_LT\" INT4 ,\"SECONDARY_LT\" INT4 ,\"WIG_WAG\" INT4 ,\"REVERSE_GEAR\" INT4 ,\"CHASSIS_VOLT\" FLOAT4 ,\"CONVERS_VOLT\" FLOAT4 ,\"RADIO_VOLT\" FLOAT4 ,\"PARKING_LT\" INT4 ,\"HIGH_BEAM_LT\" INT4 ,\"SIREN\" INT4 ,\"CHECK_ENGINE\" INT4 ,\"THROTTLE\" INT4 ,\"ODOMETER\" FLOAT4 ,\"LONGITUDE\" FLOAT4 ,\"LATITUDE\" FLOAT4 ,\"IGNITION\" INT4 ,\"TIME_RUNNING\" INT4 ,\"TIME_STOP\" INT4 ,\"TIME_IDLE\" INT4 ,\"ACC_LONG\" FLOAT4 ,\"ACC_LATERAL\" FLOAT8 ,\"ACC_VERTICAL\" FLOAT4 ,\"FUEL_RATE\" FLOAT4 ,\"DRIVER_DOOR\" INT4 ,\"BACK_DOOR\" INT4 ,\"PARK_BRAKE\" INT4 ,\"SEAT_BELT\" INT4 ,\"AIR_BAG\" INT4 ,\"ECO_ACTIVE\" INT4 ,\"ESPAR_ACTIVE\" INT4 )");

					}
					if (conn_tCreateTable_1 != null && !conn_tCreateTable_1.isClosed()) {
						conn_tCreateTable_1.close();
					}

					globalMap.put("tCreateTable_1_QUERY", "CREATE TABLE \"" + tableName_tCreateTable_1
							+ "\"(\"id_vehicule\" SERIAL  not null ,\"DATE\" VARCHAR(19)  ,\"TIME\" VARCHAR ,\"RPM\" INT4 ,\"SPEED\" FLOAT4 ,\"RIGHT_FLASH\" INT4 ,\"LEFT_FLASH\" INT4 ,\"BRAKE_PEDAL\" INT4 ,\"PRIMARY_LT\" INT4 ,\"SECONDARY_LT\" INT4 ,\"WIG_WAG\" INT4 ,\"REVERSE_GEAR\" INT4 ,\"CHASSIS_VOLT\" FLOAT4 ,\"CONVERS_VOLT\" FLOAT4 ,\"RADIO_VOLT\" FLOAT4 ,\"PARKING_LT\" INT4 ,\"HIGH_BEAM_LT\" INT4 ,\"SIREN\" INT4 ,\"CHECK_ENGINE\" INT4 ,\"THROTTLE\" INT4 ,\"ODOMETER\" FLOAT4 ,\"LONGITUDE\" FLOAT4 ,\"LATITUDE\" FLOAT4 ,\"IGNITION\" INT4 ,\"TIME_RUNNING\" INT4 ,\"TIME_STOP\" INT4 ,\"TIME_IDLE\" INT4 ,\"ACC_LONG\" FLOAT4 ,\"ACC_LATERAL\" FLOAT8 ,\"ACC_VERTICAL\" FLOAT4 ,\"FUEL_RATE\" FLOAT4 ,\"DRIVER_DOOR\" INT4 ,\"BACK_DOOR\" INT4 ,\"PARK_BRAKE\" INT4 ,\"SEAT_BELT\" INT4 ,\"AIR_BAG\" INT4 ,\"ECO_ACTIVE\" INT4 ,\"ESPAR_ACTIVE\" INT4 )");
				} catch (java.lang.Exception e) {
					globalMap.put("tCreateTable_1_ERROR_MESSAGE", e.getMessage());
					throw new RuntimeException("Creating table failed", e);
				}

				tos_count_tCreateTable_1++;

				/**
				 * [tCreateTable_1 main ] stop
				 */

				/**
				 * [tCreateTable_1 process_data_begin ] start
				 */

				currentComponent = "tCreateTable_1";

				/**
				 * [tCreateTable_1 process_data_begin ] stop
				 */

				/**
				 * [tCreateTable_1 process_data_end ] start
				 */

				currentComponent = "tCreateTable_1";

				/**
				 * [tCreateTable_1 process_data_end ] stop
				 */

				/**
				 * [tCreateTable_1 end ] start
				 */

				currentComponent = "tCreateTable_1";

				ok_Hash.put("tCreateTable_1", true);
				end_Hash.put("tCreateTable_1", System.currentTimeMillis());

				if (execStat) {
					runStat.updateStatOnConnection("OnComponentOk2", 0, "ok");
				}
				tCreateTable_2Process(globalMap);

				/**
				 * [tCreateTable_1 end ] stop
				 */
			} // end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tCreateTable_1 finally ] start
				 */

				currentComponent = "tCreateTable_1";

				/**
				 * [tCreateTable_1 finally ] stop
				 */
			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tCreateTable_1_SUBPROCESS_STATE", 1);
	}

	public void tCreateTable_2Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tCreateTable_2_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				/**
				 * [tCreateTable_2 begin ] start
				 */

				ok_Hash.put("tCreateTable_2", false);
				start_Hash.put("tCreateTable_2", System.currentTimeMillis());

				currentComponent = "tCreateTable_2";

				int tos_count_tCreateTable_2 = 0;

				/**
				 * [tCreateTable_2 begin ] stop
				 */

				/**
				 * [tCreateTable_2 main ] start
				 */

				currentComponent = "tCreateTable_2";

				try {
					String driverClass_tCreateTable_2 = "org.postgresql.Driver";
					String url_tCreateTable_2 = "jdbc:postgresql://" + "localhost" + ":" + "5432" + "/" + "ambulance";
					String dbUser_tCreateTable_2 = "postgres";

					String tableName_tCreateTable_2 = "pos_traitee";
					String dbSchema_tCreateTable_2 = "public";
					if (dbSchema_tCreateTable_2 != null && dbSchema_tCreateTable_2.trim().length() != 0) {
						tableName_tCreateTable_2 = dbSchema_tCreateTable_2 + "\".\"" + tableName_tCreateTable_2;
					}
					java.lang.Class jdbcclazz_tCreateTable_2 = java.lang.Class.forName("org.postgresql.Driver");
					final String decryptedPassword_tCreateTable_2 = routines.system.PasswordEncryptUtil
							.decryptPassword("Wc5JN7QOl+hOSS4VvmpEAQ==");
					java.sql.Connection conn_tCreateTable_2 = java.sql.DriverManager.getConnection(url_tCreateTable_2,
							dbUser_tCreateTable_2, decryptedPassword_tCreateTable_2);

					boolean whetherExist_tCreateTable_2 = false;
					java.sql.DatabaseMetaData dbMetaData_tCreateTable_2 = conn_tCreateTable_2.getMetaData();
					java.sql.ResultSet rsTable_tCreateTable_2 = dbMetaData_tCreateTable_2.getTables(null, null, null,
							new String[] { "TABLE" });
					String defaultSchema_tCreateTable_2 = "public";
					if (dbSchema_tCreateTable_2 == null || dbSchema_tCreateTable_2.trim().length() == 0) {
						java.sql.Statement stmtSchema_tCreateTable_2 = conn_tCreateTable_2.createStatement();
						java.sql.ResultSet rsSchema_tCreateTable_2 = stmtSchema_tCreateTable_2
								.executeQuery("select current_schema() ");
						while (rsSchema_tCreateTable_2.next()) {
							defaultSchema_tCreateTable_2 = rsSchema_tCreateTable_2.getString("current_schema");
						}
						rsSchema_tCreateTable_2.close();
						stmtSchema_tCreateTable_2.close();
					}
					while (rsTable_tCreateTable_2.next()) {
						String table_tCreateTable_2 = rsTable_tCreateTable_2.getString("TABLE_NAME");
						String schema_tCreateTable_2 = rsTable_tCreateTable_2.getString("TABLE_SCHEM");
						if (table_tCreateTable_2.equals("pos_traitee") && (schema_tCreateTable_2
								.equals(dbSchema_tCreateTable_2)
								|| ((dbSchema_tCreateTable_2 == null || dbSchema_tCreateTable_2.trim().length() == 0)
										&& defaultSchema_tCreateTable_2.equals(schema_tCreateTable_2)))) {
							whetherExist_tCreateTable_2 = true;
							break;
						}
					}
					rsTable_tCreateTable_2.close();
					if (!whetherExist_tCreateTable_2) {
						java.sql.Statement stmt_tCreateTable_2 = conn_tCreateTable_2.createStatement();
						stmt_tCreateTable_2.execute("CREATE TABLE \"" + tableName_tCreateTable_2
								+ "\"(\"id_ligne\" SERIAL  not null ,\"id_vehicule\" INT4  not null ,\"DATE\" TIMESTAMP  not null ,\"RPM\" INT4 ,\"SPEED\" FLOAT4 ,\"RIGHT_FLASH\" INT4 ,\"LEFT_FLASH\" INT4 ,\"BRAKE_PEDAL\" INT4 ,\"PRIMARY_LT\" INT4 ,\"WIG_WAG\" INT4 ,\"REVERSE_GEAR\" INT4 ,\"CHASSIS_VOLT\" FLOAT4 ,\"CONVERS_VOLT\" FLOAT4 ,\"PARKING_LT\" INT4 ,\"HIGH_BEAM_LT\" INT4 ,\"SIREN\" INT4 ,\"CHECK_ENGINE\" INT4 ,\"THROTTLE\" INT4 ,\"ODOMETER\" FLOAT4 ,\"LONGITUDE\" FLOAT4 ,\"LATITUDE\" FLOAT4 ,\"IGNITION\" INT4 ,\"TIME_RUNNING\" INT4 ,\"TIME_STOP\" INT4 ,\"TIME_IDLE\" INT4 ,\"ACC_LONG\" FLOAT4 ,\"ACC_LATERAL\" FLOAT8 ,\"ACC_VERTICAL\" FLOAT4 ,\"FUEL_RATE\" FLOAT4 ,\"DRIVER_DOOR\" INT4 ,\"BACK_DOOR\" INT4 ,\"PARK_BRAKE\" INT4 ,\"SEAT_BELT\" INT4 ,\"AIR_BAG\" INT4 ,\"ECO_ACTIVE\" INT4 ,\"geom4326\" FLOAT4 ,\"geom2154\" FLOAT4 ,\"CONCAT1\" INT4 default 0 ,primary key(\"id_ligne\"))");

					}
					if (conn_tCreateTable_2 != null && !conn_tCreateTable_2.isClosed()) {
						conn_tCreateTable_2.close();
					}

					globalMap.put("tCreateTable_2_QUERY", "CREATE TABLE \"" + tableName_tCreateTable_2
							+ "\"(\"id_ligne\" SERIAL  not null ,\"id_vehicule\" INT4  not null ,\"DATE\" TIMESTAMP  not null ,\"RPM\" INT4 ,\"SPEED\" FLOAT4 ,\"RIGHT_FLASH\" INT4 ,\"LEFT_FLASH\" INT4 ,\"BRAKE_PEDAL\" INT4 ,\"PRIMARY_LT\" INT4 ,\"WIG_WAG\" INT4 ,\"REVERSE_GEAR\" INT4 ,\"CHASSIS_VOLT\" FLOAT4 ,\"CONVERS_VOLT\" FLOAT4 ,\"PARKING_LT\" INT4 ,\"HIGH_BEAM_LT\" INT4 ,\"SIREN\" INT4 ,\"CHECK_ENGINE\" INT4 ,\"THROTTLE\" INT4 ,\"ODOMETER\" FLOAT4 ,\"LONGITUDE\" FLOAT4 ,\"LATITUDE\" FLOAT4 ,\"IGNITION\" INT4 ,\"TIME_RUNNING\" INT4 ,\"TIME_STOP\" INT4 ,\"TIME_IDLE\" INT4 ,\"ACC_LONG\" FLOAT4 ,\"ACC_LATERAL\" FLOAT8 ,\"ACC_VERTICAL\" FLOAT4 ,\"FUEL_RATE\" FLOAT4 ,\"DRIVER_DOOR\" INT4 ,\"BACK_DOOR\" INT4 ,\"PARK_BRAKE\" INT4 ,\"SEAT_BELT\" INT4 ,\"AIR_BAG\" INT4 ,\"ECO_ACTIVE\" INT4 ,\"geom4326\" FLOAT4 ,\"geom2154\" FLOAT4 ,\"CONCAT1\" INT4 default 0 ,primary key(\"id_ligne\"))");
				} catch (java.lang.Exception e) {
					globalMap.put("tCreateTable_2_ERROR_MESSAGE", e.getMessage());
					throw new RuntimeException("Creating table failed", e);
				}

				tos_count_tCreateTable_2++;

				/**
				 * [tCreateTable_2 main ] stop
				 */

				/**
				 * [tCreateTable_2 process_data_begin ] start
				 */

				currentComponent = "tCreateTable_2";

				/**
				 * [tCreateTable_2 process_data_begin ] stop
				 */

				/**
				 * [tCreateTable_2 process_data_end ] start
				 */

				currentComponent = "tCreateTable_2";

				/**
				 * [tCreateTable_2 process_data_end ] stop
				 */

				/**
				 * [tCreateTable_2 end ] start
				 */

				currentComponent = "tCreateTable_2";

				ok_Hash.put("tCreateTable_2", true);
				end_Hash.put("tCreateTable_2", System.currentTimeMillis());

				if (execStat) {
					runStat.updateStatOnConnection("OnComponentOk1", 0, "ok");
				}
				tDBInput_1Process(globalMap);

				/**
				 * [tCreateTable_2 end ] stop
				 */
			} // end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tCreateTable_2 finally ] start
				 */

				currentComponent = "tCreateTable_2";

				/**
				 * [tCreateTable_2 finally ] stop
				 */
			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tCreateTable_2_SUBPROCESS_STATE", 1);
	}

	public void tDBInput_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tDBInput_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				/**
				 * [tDBInput_1 begin ] start
				 */

				ok_Hash.put("tDBInput_1", false);
				start_Hash.put("tDBInput_1", System.currentTimeMillis());

				currentComponent = "tDBInput_1";

				int tos_count_tDBInput_1 = 0;

				int nb_line_tDBInput_1 = 0;
				java.sql.Connection conn_tDBInput_1 = null;
				String driverClass_tDBInput_1 = "org.postgresql.Driver";
				java.lang.Class jdbcclazz_tDBInput_1 = java.lang.Class.forName(driverClass_tDBInput_1);
				String dbUser_tDBInput_1 = "postgres";

				final String decryptedPassword_tDBInput_1 = routines.system.PasswordEncryptUtil
						.decryptPassword("Wc5JN7QOl+hOSS4VvmpEAQ==");

				String dbPwd_tDBInput_1 = decryptedPassword_tDBInput_1;

				String url_tDBInput_1 = "jdbc:postgresql://" + "localhost" + ":" + "5432" + "/" + "ambulance";

				conn_tDBInput_1 = java.sql.DriverManager.getConnection(url_tDBInput_1, dbUser_tDBInput_1,
						dbPwd_tDBInput_1);

				conn_tDBInput_1.setAutoCommit(false);

				java.sql.Statement stmt_tDBInput_1 = conn_tDBInput_1.createStatement();

				String dbquery_tDBInput_1 = "ALTER TABLE pos_traitee\nDROP COLUMN geom4326,\nDROP COLUMN geom2154,\nADD COLUMN geom4326 geometry,\nADD COLUMN geom2154 g"
						+ "eometry,\nADD constraint unique_time_vehicle UNIQUE(id_vehicule,\"DATE\");";

				globalMap.put("tDBInput_1_QUERY", dbquery_tDBInput_1);
				java.sql.ResultSet rs_tDBInput_1 = null;

				try {
					rs_tDBInput_1 = stmt_tDBInput_1.executeQuery(dbquery_tDBInput_1);
					java.sql.ResultSetMetaData rsmd_tDBInput_1 = rs_tDBInput_1.getMetaData();
					int colQtyInRs_tDBInput_1 = rsmd_tDBInput_1.getColumnCount();

					String tmpContent_tDBInput_1 = null;

					while (rs_tDBInput_1.next()) {
						nb_line_tDBInput_1++;

						/**
						 * [tDBInput_1 begin ] stop
						 */

						/**
						 * [tDBInput_1 main ] start
						 */

						currentComponent = "tDBInput_1";

						tos_count_tDBInput_1++;

						/**
						 * [tDBInput_1 main ] stop
						 */

						/**
						 * [tDBInput_1 process_data_begin ] start
						 */

						currentComponent = "tDBInput_1";

						/**
						 * [tDBInput_1 process_data_begin ] stop
						 */

						/**
						 * [tDBInput_1 process_data_end ] start
						 */

						currentComponent = "tDBInput_1";

						/**
						 * [tDBInput_1 process_data_end ] stop
						 */

						/**
						 * [tDBInput_1 end ] start
						 */

						currentComponent = "tDBInput_1";

					}
				} finally {
					if (rs_tDBInput_1 != null) {
						rs_tDBInput_1.close();
					}
					if (stmt_tDBInput_1 != null) {
						stmt_tDBInput_1.close();
					}
					if (conn_tDBInput_1 != null && !conn_tDBInput_1.isClosed()) {

						conn_tDBInput_1.commit();

						conn_tDBInput_1.close();

					}

				}
				globalMap.put("tDBInput_1_NB_LINE", nb_line_tDBInput_1);

				ok_Hash.put("tDBInput_1", true);
				end_Hash.put("tDBInput_1", System.currentTimeMillis());

				/**
				 * [tDBInput_1 end ] stop
				 */
			} // end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tDBInput_1 finally ] start
				 */

				currentComponent = "tDBInput_1";

				/**
				 * [tDBInput_1 finally ] stop
				 */
			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tDBInput_1_SUBPROCESS_STATE", 1);
	}

	public void tDBInput_2Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tDBInput_2_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				/**
				 * [tDBInput_2 begin ] start
				 */

				ok_Hash.put("tDBInput_2", false);
				start_Hash.put("tDBInput_2", System.currentTimeMillis());

				currentComponent = "tDBInput_2";

				int tos_count_tDBInput_2 = 0;

				int nb_line_tDBInput_2 = 0;
				java.sql.Connection conn_tDBInput_2 = null;
				String driverClass_tDBInput_2 = "org.postgresql.Driver";
				java.lang.Class jdbcclazz_tDBInput_2 = java.lang.Class.forName(driverClass_tDBInput_2);
				String dbUser_tDBInput_2 = "postgres";

				final String decryptedPassword_tDBInput_2 = routines.system.PasswordEncryptUtil
						.decryptPassword("Wc5JN7QOl+hOSS4VvmpEAQ==");

				String dbPwd_tDBInput_2 = decryptedPassword_tDBInput_2;

				String url_tDBInput_2 = "jdbc:postgresql://" + "localhost" + ":" + "5432" + "/" + "ambulance";

				conn_tDBInput_2 = java.sql.DriverManager.getConnection(url_tDBInput_2, dbUser_tDBInput_2,
						dbPwd_tDBInput_2);

				conn_tDBInput_2.setAutoCommit(false);

				java.sql.Statement stmt_tDBInput_2 = conn_tDBInput_2.createStatement();

				String dbquery_tDBInput_2 = "CREATE INDEX idx_concat1\nON public.pos_traitee USING btree(\"CONCAT1\")\nTABLESPACE pg_default;\n\nCREATE INDEX idx_dateti"
						+ "me\nON public.pos_traitee USING btree(\"DATE\")\nTABLESPACE pg_default;\n\nCREATE INDEX idx_id_ligne_pos_traitee\nON public.p"
						+ "os_traitee USING btree(id_ligne)\nTABLESPACE pg_default;\n\nALTER TABLE public.pos_traitee\nCLUSTER ON idx_id_ligne_pos_trai"
						+ "tee;\n\nCREATE INDEX idx_pos_traitee_geom2154\nON public.pos_traitee USING gist(geom2154)\nTABLESPACE pg_default;\n\nCREATE IN"
						+ "DEX idx_pos_traitee_geom4326\nON public.pos_traitee USING gist(geom4326)\nTABLESPACE pg_default;";

				globalMap.put("tDBInput_2_QUERY", dbquery_tDBInput_2);
				java.sql.ResultSet rs_tDBInput_2 = null;

				try {
					rs_tDBInput_2 = stmt_tDBInput_2.executeQuery(dbquery_tDBInput_2);
					java.sql.ResultSetMetaData rsmd_tDBInput_2 = rs_tDBInput_2.getMetaData();
					int colQtyInRs_tDBInput_2 = rsmd_tDBInput_2.getColumnCount();

					String tmpContent_tDBInput_2 = null;

					while (rs_tDBInput_2.next()) {
						nb_line_tDBInput_2++;

						/**
						 * [tDBInput_2 begin ] stop
						 */

						/**
						 * [tDBInput_2 main ] start
						 */

						currentComponent = "tDBInput_2";

						tos_count_tDBInput_2++;

						/**
						 * [tDBInput_2 main ] stop
						 */

						/**
						 * [tDBInput_2 process_data_begin ] start
						 */

						currentComponent = "tDBInput_2";

						/**
						 * [tDBInput_2 process_data_begin ] stop
						 */

						/**
						 * [tDBInput_2 process_data_end ] start
						 */

						currentComponent = "tDBInput_2";

						/**
						 * [tDBInput_2 process_data_end ] stop
						 */

						/**
						 * [tDBInput_2 end ] start
						 */

						currentComponent = "tDBInput_2";

					}
				} finally {
					if (rs_tDBInput_2 != null) {
						rs_tDBInput_2.close();
					}
					if (stmt_tDBInput_2 != null) {
						stmt_tDBInput_2.close();
					}
					if (conn_tDBInput_2 != null && !conn_tDBInput_2.isClosed()) {

						conn_tDBInput_2.commit();

						conn_tDBInput_2.close();

					}

				}
				globalMap.put("tDBInput_2_NB_LINE", nb_line_tDBInput_2);

				ok_Hash.put("tDBInput_2", true);
				end_Hash.put("tDBInput_2", System.currentTimeMillis());

				/**
				 * [tDBInput_2 end ] stop
				 */
			} // end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tDBInput_2 finally ] start
				 */

				currentComponent = "tDBInput_2";

				/**
				 * [tDBInput_2 finally ] stop
				 */
			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tDBInput_2_SUBPROCESS_STATE", 1);
	}

	public String resuming_logs_dir_path = null;
	public String resuming_checkpoint_path = null;
	public String parent_part_launcher = null;
	private String resumeEntryMethodName = null;
	private boolean globalResumeTicket = false;

	public boolean watch = false;
	// portStats is null, it means don't execute the statistics
	public Integer portStats = null;
	public int portTraces = 4334;
	public String clientHost;
	public String defaultClientHost = "localhost";
	public String contextStr = "Default";
	public boolean isDefaultContext = true;
	public String pid = "0";
	public String rootPid = null;
	public String fatherPid = null;
	public String fatherNode = null;
	public long startTime = 0;
	public boolean isChildJob = false;
	public String log4jLevel = "";

	private boolean execStat = true;

	private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
		protected java.util.Map<String, String> initialValue() {
			java.util.Map<String, String> threadRunResultMap = new java.util.HashMap<String, String>();
			threadRunResultMap.put("errorCode", null);
			threadRunResultMap.put("status", "");
			return threadRunResultMap;
		};
	};

	private PropertiesWithType context_param = new PropertiesWithType();
	public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

	public String status = "";

	public static void main(String[] args) {
		final COLD_START_MASTER_JOB COLD_START_MASTER_JOBClass = new COLD_START_MASTER_JOB();

		int exitCode = COLD_START_MASTER_JOBClass.runJobInTOS(args);

		System.exit(exitCode);
	}

	public String[][] runJob(String[] args) {

		int exitCode = runJobInTOS(args);
		String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

		return bufferValue;
	}

	public boolean hastBufferOutputComponent() {
		boolean hastBufferOutput = false;

		return hastBufferOutput;
	}

	public int runJobInTOS(String[] args) {
		// reset status
		status = "";

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		if (pid == null || "0".equals(pid)) {
			pid = TalendString.getAsciiRandomString(6);
		}

		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		} else {
			isChildJob = true;
		}

		if (portStats != null) {
			// portStats = -1; //for testing
			if (portStats < 0 || portStats > 65535) {
				// issue:10869, the portStats is invalid, so this client socket can't open
				System.err.println("The statistics socket port " + portStats + " is invalid.");
				execStat = false;
			}
		} else {
			execStat = false;
		}

		try {
			// call job/subjob with an existing context, like: --context=production. if
			// without this parameter, there will use the default context instead.
			java.io.InputStream inContext = COLD_START_MASTER_JOB.class.getClassLoader().getResourceAsStream(
					"local_project/cold_start_master_job_0_1/contexts/" + contextStr + ".properties");
			if (inContext == null) {
				inContext = COLD_START_MASTER_JOB.class.getClassLoader()
						.getResourceAsStream("config/contexts/" + contextStr + ".properties");
			}
			if (inContext != null) {
				// defaultProps is in order to keep the original context value
				if (context != null && context.isEmpty()) {
					defaultProps.load(inContext);
					context = new ContextProperties(defaultProps);
				}

				inContext.close();
			} else if (!isDefaultContext) {
				// print info and job continue to run, for case: context_param is not empty.
				System.err.println("Could not find the context " + contextStr);
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
				// set types for params from parentJobs
				for (Object key : context_param.keySet()) {
					String context_key = key.toString();
					String context_type = context_param.getContextType(context_key);
					context.setContextType(context_key, context_type);

				}
			}
			class ContextProcessing {
				private void processContext_0() {
				}

				public void processAllContext() {
					processContext_0();
				}
			}

			new ContextProcessing().processAllContext();
		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		// get context value from parent directly
		if (parentContextMap != null && !parentContextMap.isEmpty()) {
		}

		// Resume: init the resumeUtil
		resumeEntryMethodName = ResumeUtil.getResumeEntryMethodName(resuming_checkpoint_path);
		resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
		resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName, jobName, contextStr, jobVersion);

		List<String> parametersToEncrypt = new java.util.ArrayList<String>();
		// Resume: jobStart
		resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "",
				"", "", "", "", resumeUtil.convertToJsonText(context, parametersToEncrypt));

		if (execStat) {
			try {
				runStat.openSocket(!isChildJob);
				runStat.setAllPID(rootPid, fatherPid, pid, jobName);
				runStat.startThreadStat(clientHost, portStats);
				runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
			} catch (java.io.IOException ioException) {
				ioException.printStackTrace();
			}
		}

		java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
		globalMap.put("concurrentHashMap", concurrentHashMap);

		long startUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		long endUsedMemory = 0;
		long end = 0;

		startTime = System.currentTimeMillis();

		this.globalResumeTicket = true;// to run tPreJob

		this.globalResumeTicket = false;// to run others jobs

		try {
			errorCode = null;
			tCreateTable_1Process(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}
		} catch (TalendException e_tCreateTable_1) {
			globalMap.put("tCreateTable_1_SUBPROCESS_STATE", -1);

			e_tCreateTable_1.printStackTrace();

		}

		this.globalResumeTicket = true;// to run tPostJob

		end = System.currentTimeMillis();

		if (watch) {
			System.out.println((end - startTime) + " milliseconds");
		}

		endUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		if (false) {
			System.out.println(
					(endUsedMemory - startUsedMemory) + " bytes memory increase when running : COLD_START_MASTER_JOB");
		}

		if (execStat) {
			runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
			runStat.stopThreadStat();
		}
		int returnCode = 0;
		if (errorCode == null) {
			returnCode = status != null && status.equals("failure") ? 1 : 0;
		} else {
			returnCode = errorCode.intValue();
		}
		resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "",
				"" + returnCode, "", "", "");

		return returnCode;

	}

	// only for OSGi env
	public void destroy() {

	}

	private java.util.Map<String, Object> getSharedConnections4REST() {
		java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();

		return connections;
	}

	private void evalParam(String arg) {
		if (arg.startsWith("--resuming_logs_dir_path")) {
			resuming_logs_dir_path = arg.substring(25);
		} else if (arg.startsWith("--resuming_checkpoint_path")) {
			resuming_checkpoint_path = arg.substring(27);
		} else if (arg.startsWith("--parent_part_launcher")) {
			parent_part_launcher = arg.substring(23);
		} else if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			String portStatsStr = arg.substring(12);
			if (portStatsStr != null && !portStatsStr.equals("null")) {
				portStats = Integer.parseInt(portStatsStr);
			}
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
			isDefaultContext = false;
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--father_node=")) {
			fatherNode = arg.substring(14);
		} else if (arg.startsWith("--pid=")) {
			pid = arg.substring(6);
		} else if (arg.startsWith("--context_type")) {
			String keyValue = arg.substring(15);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.setContextType(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.setContextType(keyValue.substring(0, index), keyValue.substring(index + 1));
				}

			}

		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.put(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.put(keyValue.substring(0, index), keyValue.substring(index + 1));
				}
			}
		} else if (arg.startsWith("--log4jLevel=")) {
			log4jLevel = arg.substring(13);
		}

	}

	private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY = "<TALEND_NULL>";

	private final String[][] escapeChars = { { "\\\\", "\\" }, { "\\n", "\n" }, { "\\'", "\'" }, { "\\r", "\r" },
			{ "\\f", "\f" }, { "\\b", "\b" }, { "\\t", "\t" } };

	private String replaceEscapeChars(String keyValue) {

		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}

		StringBuilder result = new StringBuilder();
		int currIndex = 0;
		while (currIndex < keyValue.length()) {
			int index = -1;
			// judege if the left string includes escape chars
			for (String[] strArray : escapeChars) {
				index = keyValue.indexOf(strArray[0], currIndex);
				if (index >= 0) {

					result.append(keyValue.substring(currIndex, index + strArray[0].length()).replace(strArray[0],
							strArray[1]));
					currIndex = index + strArray[0].length();
					break;
				}
			}
			// if the left string doesn't include escape chars, append the left into the
			// result
			if (index < 0) {
				result.append(keyValue.substring(currIndex));
				currIndex = currIndex + keyValue.length();
			}
		}

		return result.toString();
	}

	public Integer getErrorCode() {
		return errorCode;
	}

	public String getStatus() {
		return status;
	}

	ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 * 47834 characters generated by Talend Open Studio for Big Data on the July 15,
 * 2019 3:52:52 PM CEST
 ************************************************************************************************/